# Generated by Django 4.2.17 on 2025-07-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_mgmt', '0005_receipt_company_phone_receipt_country_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_type',
            field=models.IntegerField(choices=[(1, 'Groceries'), (2, 'Apparel'), (3, 'Dining Out'), (4, 'Electronics'), (5, 'Supplies'), (6, 'Healthcare'), (7, 'Home'), (8, 'Utilities'), (9, 'Transportation'), (10, 'Insurance'), (11, 'Personal Care'), (12, 'Subscriptions'), (13, 'Entertainment'), (14, 'Education'), (15, 'Pets'), (16, 'Travel'), (17, 'Other')], default=17, help_text='Category of the receipt'),
        ),
    ]
