# Generated by Django 4.2.17 on 2025-07-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_mgmt', '0007_add_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='returnable_by_date',
            field=models.DateField(blank=True, help_text='Date by which this item can be returned, determined by AI analysis', null=True),
        ),
    ]
